# apiVersion: v1
# kind: Service
# metadata:
#   name: qi-monitoring-service
#   labels:
#     app: qi-monitoring-engine
# spec:
#   type: NodePort
#   selector:
#     app: qi-monitoring
#   ports:
#   - port: 7070
#     targetPort: 7070

# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qi-monitoring-listener
  labels:
    app: qi-monitoring-engine
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qi-monitoring
      tier: backend
  template:
    metadata:
      labels:
        app: qi-monitoring
        tier: backend
    spec:
      containers:
      - name: qi-monitoring
        image: 218547968715.dkr.ecr.ap-southeast-2.amazonaws.com/qi-monitoring:1.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "1000m"
          limits:
            memory: "512Mi"
            cpu: "2000m"
        envFrom:
        - configMapRef:
            name: db-cred
        - configMapRef:
            name: web3-providers
        args:
          - "listen -T"
      imagePullSecrets:
      - name: regcred