apiVersion: v1
kind: Service
metadata:
  name: qi-monitoring-db-service
  labels:
    app: qi-monitoring-db
spec:
  selector:
    app: qi-monitoring-db
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qi-monitoring-db
  labels:
    app: qi-monitoring-db
    tier: data
spec:
  selector:
    matchLabels:
      app: qi-monitoring-db
      tier: data
  template:
    metadata:
      labels:
        app: qi-monitoring-db
        tier: data
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine3.15
        resources:
          limits:
            memory: "128Mi"
            cpu: "1000m"
        env:
          - name: POSTGRES_PASSWORD
            value: mysecretpassword
        ports:
        - containerPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: qidao-monitoring-engine
    tier: data
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      tolerations:
      - key: "sd-card-speed"
        operator: "Equal"
        value: "slow"
        effect: "PreferNoSchedule"


---

apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  selector:
    app: adminer
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
