version: '3.9'
services:
  pg:
    image: postgres:alpine
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  dbVol: