export const ORACLE_WATCHER_INITIALIZED = 'oracle-watcher.initialized'
export const DELTA_ALERT_PATTERN = 'oracle-watcher.delta-alert'
export const ORACLE_WATCHER_REGISTER_ASSET = 'oracle-watcher.register-asset'
export const ORACLE_WATCHER_REGISTER_PRICE_SOURCE = 'oracle-watcher.register-price-source'
export const ORACLE_WATCHER_CREATE_DELTA_ALERT = 'oracle-watcher.create-delta-alert'
export const ORACLE_WATCHER_UPDATE_DELTA_ALERT = 'oracle-watcher.update-delta-alert'
